### ISSUE TITLE
FInal Phase of the project

### ISSUE THREAD

**Issue by Icon1cc** [jakob-forstmann/sentiment-analysis-of-youtube-comments#17]
1) Queries related to our ideas and model. Does it align by the principles of the project? Please guide us if we did something incorrectly or if something is still missing in our project.

2) We would like you to please give a feedback on the following aspects:

1) Data pre-preprocessing
2) Training the model
3) Front end and Back end development
4) Overall completion and ideas

**Comment by dennlinger** [comment]
* Can you clarify what you mean by "queries" in Point 1? 
* Also, you have a lot of branches, and I'm not going to review all of them; please let me know if there is relevant content on one of them, otherwise I'll restrict myself to `main` for the review.
* Regarding points 2-5: These are all fairly general, and basically capture the entirety of the project. You need to be more specific in case you want to have some actionable feedback.
