### ISSUE TITLE
fetch comments from random YouTube videos and label them as test set

### ISSUE THREAD

**Issue by hirschjn** [jakob-forstmann/sentiment-analysis-of-youtube-comments#9]

**Comment by Icon1cc** [comment]
1) Fetched Youtube Comments using the code: 

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import csv

api_key = "My API Key"
api_service_name = "youtube"
api_version = "v3"

youtube = build(api_service_name, api_version, developerKey=api_key)

request = youtube.commentThreads().list(
    part="snippet",
    videoId="wA5JDqSXZXI",
    maxResults=50,
    textFormat="plainText"
)
response = request.execute()

with open("comments.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["Comment"])

    # Iterate through the comments and write them to the CSV file
    for item in response["items"]:
        comment = item["snippet"]["topLevelComment"]["snippet"]["textDisplay"]
        writer.writerow([comment])

Fetched 2500 Youtube comments and labelled them manually in three categories: 

1) Positive 
2) Neutral
3) Negative

Before labelling the Youtube Comments, it was pre-processed in order to make it a simple english line so that it will be easier to extract the sentimental words and label them accordingly.

After labelling further steps were being in progress for further training of the models using vector machines.
